# Generated by Django 4.1.1 on 2022-10-09 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_coursefeedback_rating_alter_courses_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=30, verbose_name='cost'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='cover',
            field=models.ImageField(upload_to='images/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='name',
            field=models.CharField(max_length=256, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='update'),
        ),
        migrations.AlterField(
            model_name='courseteachers',
            name='course',
            field=models.ManyToManyField(to='mainapp.courses', verbose_name='course'),
        ),
        migrations.AlterField(
            model_name='courseteachers',
            name='day_birth',
            field=models.DateField(verbose_name='birth'),
        ),
        migrations.AlterField(
            model_name='courseteachers',
            name='name_first',
            field=models.CharField(max_length=256, verbose_name='name_first'),
        ),
        migrations.AlterField(
            model_name='courseteachers',
            name='name_second',
            field=models.CharField(max_length=256, verbose_name='name_second'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.courses', verbose_name='course'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='num',
            field=models.DecimalField(decimal_places=0, max_digits=30, verbose_name='num'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=256, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='update'),
        ),
        migrations.AlterField(
            model_name='news',
            name='body',
            field=models.TextField(verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='news',
            name='body_as_markdown',
            field=models.BooleanField(default=False, verbose_name='body_as_markdown'),
        ),
        migrations.AlterField(
            model_name='news',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='news',
            name='preambule',
            field=models.TextField(verbose_name='preambule'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=256, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='news',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='update'),
        ),
    ]
