# Generated by Django 4.1.1 on 2022-10-06 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
